name: Lint, Test and Deploy Charts
on:
  push:
  pull_request:

jobs:
  lint-test:
    name: "Lint and Test"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0

      - name: "Set Up Helm"
        uses: azure/setup-helm@v3.3
        with:
          version: v3.4.1

      - name: "Set Up Python"
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.9

      - name: "Set up chart-testing"
        uses: helm/chart-testing-action@v2.3.0
        with:
          version: v3.3.0

      - name: "Run chart-testing (list-changed)"
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: "Run chart-testing (lint)"
        run: ct lint --config ct.yaml
        if: steps.list-changed.outputs.changed == 'true'

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml
        if: steps.list-changed.outputs.changed == 'true'

      - name: Get Branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

  release_on_nexus:
    name: Release Chart on Nexus
    runs-on: ubuntu-22.04
    needs: lint-test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Run chart-releaser
        uses: ntwklr/nexus-helm-chart-releaser-action@v0.0.5
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_repo_url: https://repo.mahahe.it/repository/helm/
          username: "${{ secrets.NEXUS_USERNAME }}"
          password: "${{ secrets.NEXUS_PASSWORD }}"
