name: Release Charts

on:
  repository_dispatch:
    types: [lint-successful]
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodule: recusive
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo
        run: |
          pwd
          ls -la
          cd hugo
          pwd
          ls -la
          hugo --minify
          pwd
          ls -la
          cd public
          pwd
          ls -la
          cd ..
          cd themes/terminal
          ls -la
          cd ..
          cd ..
          cat config.yaml
          cd content
          ls -la
          cat index.md
          cd ..
          cp -r ./public ../public
          cd ..
      
      - name: Delpoy Hugo
        uses: peaceiris/actions-gh-pages@v3
        # if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          
